# Prometheus configuration for Bazari Marketplace monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bazari-production'
    service: 'ethnic-clothing-marketplace'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Next.js Application
  - job_name: 'bazari-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'app:3000'

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Supabase Metrics (if available)
  - job_name: 'supabase'
    static_configs:
      - targets: ['supabase-exporter:9090']
    scrape_interval: 60s
    honor_labels: true

  # Custom Application Metrics
  - job_name: 'bazari-custom-metrics'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/monitoring/metrics'
    scrape_interval: 30s
    params:
      type: ['custom']

  # Trust & Safety Metrics
  - job_name: 'trust-safety-metrics'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/trust-safety/metrics'
    scrape_interval: 60s

  # Cultural Analytics Metrics
  - job_name: 'cultural-metrics'    
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/cultural-education/metrics'
    scrape_interval: 120s

# Remote write configuration (for long-term storage)
remote_write:
  - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
    basic_auth:
      username: "${GRAFANA_CLOUD_USERNAME}"
      password: "${GRAFANA_CLOUD_API_KEY}"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: "bazari_.*"
        action: keep

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true